dist: bionic
sudo: required
launguage: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - cmake-data

before_install:
  - pip install --user cpp-coveralls

install:
  - sudo apt update -qq
  - sudo apt install -qq libboost-all-dev
  - sudo apt-get install -y -qq lcov


before_script:
  - git clone https://github.com/google/googletest.git    lib/googletest
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ../
  - make
  - make code_coverage
  - ./test/pathPlanning

after_sucess:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false