dist: bionic
sudo: required
launguage: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: 
      - lcov
      - gcc-7
      - g++-7
      - cmake

install:
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev

before_script:
  - git clone https://github.com/google/googletest.git    lib/googletest
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake
  - make
  - /pathPlanning
  - ./test/pathPlanning

after_sucess:
  - cd ~/path_planning_2D/build
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/opt/*' '/usr/*' '*/devel/*' '*test_*' '*_test*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov coverage.info

notifications:
  email: false