/**
 * BSD 3-Clause License
 * Copyright (c) 2020, Kapil Rawal
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 * Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *  @copyright (c) BSD
 *
 *  @file   path_planning.h
 *
 *  @author   Kapil Rawal (kapilrawal1995@gmail.com)
 *
 *  @copyright   BSD License
 *
 *  @brief   PathPlanning class header file
 *
 *  @section   DESCRIPTION
 *
 *  File structure containing the definations of PathPlanning class
 *
 */

#ifndef INCLUDE_PATH_PLANNING_
#define INCLUDE_PATH_PLANNING_

#include <boost/optional.hpp>
#include <vector>
#include <string>
#include <set>

/**
 * @brief PathPlanning class defination
 * 
 */
class PathPlanning {
 private:
	int MIN_GRID_SIZE;
	int TOTAL_NEIGHBOURS;
    typedef boost::optional<std::pair<int,int>> index;
	index start_;
    index goal_;
    bool initalized_flag_;
    std::vector<std::vector<int>> grid_;

 public:
    /**
     * @brief Construct a new Path Planning object
     * 
     */
    PathPlanning();
    /**
     * @brief Destroy the Path Planning object
     * 
     */
    ~PathPlanning();
    /**
     * @brief Main planner method which encloses other methods
     * 
     * @param input_grid input grid to be used as 2D map for search
     * @param start  start position for the planner
     * @param goal goal position to be reached by the planner
     * @param generatedPath pointer of generated path sent by user 
     * @param plannerType Name of the planner to be used
     */
    void plannerMain(const std::vector<std::vector<int>>& input_grid, 
                  index start, index goal,
                  std::vector<index> *generatedPath,
                  const std::string plannerType);
    /**
     * @brief Set the Parameters for the PathPlanning class
     * 
     * @param input_grid input grid to be used as 2D map for search
     * @param start start position for the planner
     * @param goal goal position to be reached by the planner
     * @return true if values are able to get set
     * @return false if one of the input is invalid
     */
    bool setParams(const std::vector<std::vector<int>>& input_grid, 
                   index start, index goal);
    /**
     * @brief Checks if the input grid is valid
     * 
     * @param input_grid input grid to be used as 2D map for search
     * @return true if grid is valid and passes all conditons
     * @return false null or invalid grid 
     */
    bool validGrid(const std::vector<std::vector<int>>& input_grid);
    /**
     * @brief Checks if the given position is available on the grid
     * 
     * @param input_grid input grid to be used as 2D map for search
     * @param position a point on the grid
     * @return true if the given position is within grid limits and not on obstacles
     * @return false if it is outside of grid or on obstacle
     */
    bool validPosition(const std::vector<std::vector<int>>& input_grid, 
                       index position);
    /**
     * @brief Calls the relevent path planner method for finding the path
     * 
     * @param generatedPath pointer to path that will be generated by the planner
     * @param plannerType name of the plannner to be used
     */
    void pathPlanner(std::vector<index>* generatedPath,
                     const std::string plannerType);
    /**
     * @brief Generating neighbours for a praticular input node
     * 
     * @param neighbours pointer to neighbours to be generated
     * @param grid input grid on which neighbours are to be found
     * @param visited_set set of visited values, helps to avoid reselecting alrady visited nodes
     * @param node node whoes neighbours has to be found
     */
	void generateNeighbour(std::vector<index> *neighbours,
                           std::set<index> *visited_set,
                           const std::vector<std::vector<int>>& grid,
                           const index node);
    /**
     * @brief Dijkstra Shortest Path, Path Planning algorithm
     * 
     * @param generatedPath pointer to the path being generated by dijkstra algorithm
     */
	void dijkstra(std::vector<index>* generatedPath);
};

#endif  //  INCLUDE_PATH_PLANNING_
